src/PearAdmin.AbpTemplate.Admin/Models/OrganizationUnits/GetPagedOrganizationUnitViewModel.cs
using Abp.AutoMapper;
using PearAdmin.AbpTemplate.Organizations.Dto;
using PearAdmin.AbpTemplate.Admin.Models.Common;

namespace PearAdmin.AbpTemplate.Admin.Models.OrganizationUnits
{
    /// <summary>
    /// 组织机构分页模型
    /// </summary>
    [AutoMapTo(typeof(GetPagedOrganizationUnitInput))]
    public class GetPagedOrganizationUnitViewModel : PagedViewModel
    {
        public long? Id { get; set; }

        public string DisplayName { get; set; }
    }
}

src/PearAdmin.AbpTemplate.Admin/Models/OrganizationUnits/OrganizationUnitListViewModel.cs
using Abp.AutoMapper;
using PearAdmin.AbpTemplate.Organizations.Dto;
using PearAdmin.AbpTemplate.Admin.Models.Common;

namespace PearAdmin.AbpTemplate.Admin.Models.OrganizationUnits
{
    /// <summary>
    /// 组织机构视图模型
    /// </summary>
    [AutoMap(typeof(OrganizationUnitDto))]
    public class OrganizationUnitListViewModel : EntityViewModel<long>
    {
        public long? ParentId { get; set; }

        public string DisplayName { get; set; }

        public bool Checked { get; set; } = false;
    }
}

src/PearAdmin.AbpTemplate.Admin/Models/OrganizationUnits/OrganizationUnitRequestViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PearAdmin.AbpTemplate.Admin.Models.OrganizationUnits
{
    /// <summary>
    /// 组织机构请求参数视图模型
    /// </summary>
    public class OrganizationUnitRequestViewModel
    {
        /// <summary>
        /// 目标组织机构Id
        /// </summary>
        public long? Id { get; set; }

        /// <summary>
        /// 组织机构父级Id
        /// </summary>
        public long? ParentId { get; set; }
    }
}

src/PearAdmin.AbpTemplate.Admin/Controllers/OrganizationUnitsController.cs
using Microsoft.AspNetCore.Mvc;
using Abp.AspNetCore.Mvc.Authorization;
using PearAdmin.AbpTemplate.Organizations;
using System.Threading.Tasks;
using PearAdmin.AbpTemplate.Admin.Models.Common;
using Abp.Application.Services.Dto;
using System.Collections.Generic;
using PearAdmin.AbpTemplate.Organizations.Dto;
using PearAdmin.AbpTemplate.Admin.Models.OrganizationUnits;
using Abp.Web.Models;

namespace PearAdmin.AbpTemplate.Admin.Controllers
{
    /// <summary>
    /// 组织机构控制器
    /// </summary>
    [AbpMvcAuthorize]
    public class OrganizationUnitsController : AbpTemplateControllerBase
    {
        #region 初始化
        private readonly IOrganizationUnitAppService _organizationUnitAppService;

        public OrganizationUnitsController(IOrganizationUnitAppService organizationUnitAppService)
        {
            _organizationUnitAppService = organizationUnitAppService;
        }
        #endregion

        /// <summary>
        /// 组织机构首页
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 获取组织机构列表
        /// </summary>
        /// <returns></returns>
        [DontWrapResult]
        public async Task<JsonResult> GetOrganizationUnitList()
        {
            var organizationUnitDtos = await _organizationUnitAppService.GetAllOrganizationUnitTree();
            return Json(new ResponseParamListViewModel<OrganizationUnitDto>(organizationUnitDtos.Items));
        }

        /// <summary>
        /// 获取组织机构列表
        /// </summary>
        /// <returns></returns>
        public async Task<JsonResult> GetPagedOrganizationUnit(GetPagedOrganizationUnitViewModel viewModel)
        {
            var input = PagedViewModelMapToPagedInputDto<GetPagedOrganizationUnitViewModel, GetPagedOrganizationUnitInput>(viewModel);

            var organizationList = await _organizationUnitAppService.GetPagedOrganizationUnit(input);

            return Json(new ResponseParamPagedViewModel<OrganizationUnitDto>(organizationList.TotalCount, organizationList.Items));
        }

        /// <summary>
        /// 创建或更新组织机构
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        public async Task<IActionResult> CreateOrUpdateOrganizationUnit(OrganizationUnitRequestViewModel viewModel)
        {
            var output = await _organizationUnitAppService.GetOrganizationUnitForEdit(new NullableIdDto<long>(viewModel.Id));

            if (!viewModel.Id.HasValue)
            {
                output.ParentId = viewModel.ParentId;
            }

            return View(output);
        }

        /// <summary>
        /// 创建组织机构
        /// </summary>
        /// <param name="input"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<JsonResult> CreateOrganizationUnit([FromBody]CreateOrganizationUnitDto input)
        {
            await _organizationUnitAppService.CreateOrganizationUnit(input);

            return Json(new ResponseParamViewModel(L("新增机构成功")));
        }

        /// <summary>
        /// 更新组织机构
        /// </summary>
        /// <param name="input"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<JsonResult> UpdateOrganizationUnit([FromBody]UpdateOrganizationUnitDto input)
        {
            await _organizationUnitAppService.UpdateOrganizationUnit(input);

            return Json(new ResponseParamViewModel(L("更新机构成功")));
        }

        /// <summary>
        /// 移动一个机构到另一个机构下
        /// </summary>
        /// <param name="moveOrganizationUnitInput"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<JsonResult> MoveOrganizationUnit([FromBody]MoveOrganizationUnitInput input)
        {
            var organizationUnitDto = await _organizationUnitAppService.MoveOrganizationUnit(input);

            return Json(new ResponseParamSingleViewModel<OrganizationUnitDto>(organizationUnitDto));
        }

        /// <summary>
        /// 删除组织机构
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<JsonResult> DeleteOrganizationUnit([FromBody]List<EntityDto<long>> input)
        {
            await _organizationUnitAppService.DeleteOrganizationUnit(input);

            return Json(new ResponseParamViewModel(L("删除机构成功")));
        }
    }
}

src/PearAdmin.AbpTemplate.Admin/Views/OrganizationUnits/CreateOrUpdateOrganizationUnit.cshtml
@using Abp.Json
@using PearAdmin.AbpTemplate.Organizations.Dto
@model OrganizationUnitDto

<form class="layui-form" lay-filter="organization-form" style="padding: 15px 0 0 0;">
    <input type="hidden" name="id" />
    <input type="hidden" name="parentId" />
    <div class="layui-form-item">
        <label class="layui-form-label">部门名称</label>
        <div class="layui-input-block">
            <input type="text" name="displayName" lay-verify="required" placeholder="请输入部门名称" autocomplete="off" class="layui-input">
        </div>
    </div>
    <div class="layui-form-item">
        <div class="layui-input-block">
            <button class="layui-btn layui-hide" lay-submit lay-filter="organization-submit" id="organization-submit">提交</button>
        </div>
    </div>
</form>

@section scripts{
    <script type="text/javascript">
        layui.use(['abp', 'form'], function () {
            var $ = layui.$;
            var abp = layui.abp;
            var form = layui.form;

            var index = parent.layer.getFrameIndex(window.name);
            parent.layer.iframeAuto(index);

            form.val("organization-form", @Html.Raw(JsonExtensions.ToJsonString(Model,true,false)));
            form.render();

            window.submitForm = function () {
                $("#organization-submit").click();
            }

            form.on('submit(organization-submit)', function (data) {
                var field = data.field;

                var waitIndex = parent.layer.load(2);
                abp.ajax({
                    url: "@Url.Action(Model.Id > 0 ?"UpdateOrganizationUnit":"CreateOrganizationUnit","OrganizationUnits")",
                    data: JSON.stringify(field),
                    abpHandleError: false
                }).done(function (data) {
                    if (data.code == 200) {
                        data.index = index;
                        let parentWindow = parent.selectedWindow().window;
                        parentWindow.saveCallback(data);
                    }
                }).fail(function (jqXHR) {
                    parent.layer.msg(jqXHR.message, { icon: 5 });
                }).always(function () {
                    parent.layer.close(waitIndex);
                });

                return false;
            });
        });
    </script>
}

src/PearAdmin.AbpTemplate.Admin/Views/OrganizationUnits/Index.cshtml
@using PearAdmin.AbpTemplate.Authorization
@using PearAdmin.AbpTemplate.Admin.Views
@{
    ViewBag.CurrentPageName = AbpTemplatePageName.OrganizationUnits;
}

@section styles{
    <style type="text/css">
        #organization-tree {
            width: 100% !important;
            height: -webkit-calc(100vh - 130px);
            height: -moz-calc(100vh - 130px);
            height: calc(100vh - 130px);
        }
    </style>
}

<div class="layui-card">
    <div class="layui-card-body">
        <form class="layui-form form-search" action="">
            <div class="layui-form-item">
                <label class="layui-form-label">机构名称</label>
                <div class="layui-input-inline">
                    <input type="text" name="displayName" placeholder="" class="layui-input">
                </div>
                <button class="pear-btn pear-btn-md pear-btn-primary" lay-submit lay-filter="organization-query">
                    <i class="layui-icon layui-icon-search"></i>
                    查询
                </button>
            </div>
        </form>
    </div>
</div>

<div class="layui-row layui-col-space15">
    <div class="layui-col-md3">
        <div class="layui-card">
            <div class="layui-card-body">
                <div style="overflow: auto">
                    <ul id="organization-tree" class="dtree"></ul>
                </div>
            </div>
        </div>
    </div>
    <div class="layui-col-md9">
        <div class="layui-card">
            <div class="layui-card-body">
                <table id="organization-table" lay-filter="organization-table"></table>
            </div>
        </div>
    </div>
</div>

<script type="text/html" id="organization-toolbar">
    @if (await PermissionChecker.IsGrantedAsync(AppPermissionNames.Pages_SystemManagement_OrganizationUnits_Create))
    {
        <button class="pear-btn pear-btn-primary pear-btn-md" lay-event="add">
            <i class="layui-icon layui-icon-add-1"></i>新增
        </button>
    }
    @if (await PermissionChecker.IsGrantedAsync(AppPermissionNames.Pages_SystemManagement_OrganizationUnits_Delete))
    {
        <button class="pear-btn pear-btn-danger pear-btn-md" lay-event="batchRemove">
            <i class="layui-icon layui-icon-delete"></i>删除
        </button>
    }
</script>

<script type="text/html" id="organization-bar">
    @if (await PermissionChecker.IsGrantedAsync(AppPermissionNames.Pages_SystemManagement_OrganizationUnits_Update))
    {
        <button class="pear-btn pear-btn-primary pear-btn-sm" lay-event="edit">
            <i class="layui-icon layui-icon-edit"></i>
        </button>
    }
    @if (await PermissionChecker.IsGrantedAsync(AppPermissionNames.Pages_SystemManagement_OrganizationUnits_Delete))
    {
        <button class="pear-btn pear-btn-danger pear-btn-sm" lay-event="remove">
            <i class="layui-icon layui-icon-delete"></i>
        </button>
    }
</script>

@section scripts{
    <script type="text/javascript">
        layui.use(['abp', 'form', 'table', 'dtree'], function () {
            var abp = layui.abp;
            var form = layui.form;
            var table = layui.table;
            var dtree = layui.dtree;

            dtree.render({
				elem: "#organization-tree",
                initLevel: "10",
                line: true,
				ficon: ["1", "-1"],
				icon: ["0", "2"],
				method: 'get',
                url: "@Url.Action("GetOrganizationUnitList", "OrganizationUnits")",
                response: {
                    message: "msg",
                    statusCode: 200,
                    title: "displayName"
                },
                dataStyle: "layuiStyle",
                dataFormat: "list"
            });

			dtree.on("node(organization-tree)", function (obj) {
                table.reload('organization-table', {
                    where: { "id": obj.param.nodeId },
					page: {
                        curr: 1
                    }
                })
			});

            table.render({
				elem: "#organization-table",
				url: "@Url.Action("GetPagedOrganizationUnit", "OrganizationUnits")",
				height: 'full-150',
				page: true,
				cols: [
				    [{
						    type: 'checkbox'
					    },
					    {
						    title: '机构名称',
						    field: 'displayName',
						    align: 'center'
					    },
					    {
						    title: '成员数量',
						    field: 'memberCount',
						    align: 'center'
					    },
					    {
						    title: '',
						    toolbar: '#organization-bar',
						    align: 'center',
						    width: 130
					    }
				    ]
                ],
                parseData: function (res) {
                    return {
                        "code": res.result.code, //解析接口状态
                        "msg": res.result.msg, //解析提示文本
                        "count": res.result.count, //解析数据长度
                        "data": res.result.data //解析数据列表
                    };
                },
                response: {
                    statusCode: 200 //规定成功的状态码，默认：0
                },
				skin: 'line',
				toolbar: '#organization-toolbar',
                defaultToolbar: [{
					layEvent: 'refresh',
					icon: 'layui-icon-refresh',
				}, 'filter', 'print', 'exports']
			});

            table.on('tool(organization-table)', function (obj) {
                var data = obj.data;
				if (obj.event === 'remove') {
					window.remove([{ "id": data.id }]);
				} else if (obj.event === 'edit') {
					window.edit(data);
				}
			});

			table.on('toolbar(organization-table)', function (obj) {
				if (obj.event === 'add') {
					window.add();
				} else if (obj.event === 'refresh') {
					window.refresh();
                } else if (obj.event === 'batchRemove') {
                    let checkData = table.checkStatus(obj.config.id).data;
				    if (checkData.length === 0) {
					    parent.layer.msg("未选中数据", {
						    icon: 3,
						    time: 1000
					    });
					    return false;
                    }
                    var ids = checkData.map(function (d) { return { "id": d.id }; });
					window.remove(ids);
				}
			});

			form.on('submit(organization-query)', function (data) {
				table.reload('organization-table', {
                    where: data.field,
					page: {
                        curr: 1
                    }
				})
				return false;
			});

            window.saveCallback = function (data) {
                parent.layer.close(data.index);
                abp.notify.success(data.msg);
                table.reload("organization-table");
                dtree.reload("organization-tree");
			}

            window.add = function () {
                let currentNode = dtree.getNowParam("organization-tree");
				parent.layer.open({
                    type: 2,
                    title: currentNode.nodeId == undefined ? '添加根组织' : '添加子节点',
                    content: "@Url.Action("CreateOrUpdateOrganizationUnit", "OrganizationUnits")" + abp.utils.formatString("?parentId={0}", currentNode.nodeId == undefined ? "" : currentNode.nodeId),
                    area: ['450px', '219px'],
                    shade: 0.1,
                    btn: ['确定', '取消'],
                    yes: function (index, layero) {
                        parent.window['layui-layer-iframe'+ index].submitForm();
                    }
                });
            }

			window.edit = function (data) {
				parent.layer.open({
                    type: 2,
                    title: '编辑机构信息',
                    content: "@Url.Action("CreateOrUpdateOrganizationUnit", "OrganizationUnits")" + abp.utils.formatString("?id={0}", data.id),
                    area: ['450px', '219px'],
                    shade: 0.1,
                    btn: ['确定', '取消'],
                    yes: function(index){
                        parent.window['layui-layer-iframe'+ index].submitForm();
                    }
                });
			}

			window.remove = function (data) {
				parent.layer.confirm('确定删除吗?',{
					icon: 3,
					title: '提示'
                }, function (index) {
                    parent.layer.close(index);
					let waitIndex = parent.layer.load(2);
                    abp.ajax({
                        url: "@Url.Action("DeleteOrganizationUnit", "OrganizationUnits")",
                        data: JSON.stringify(data),
						abpHandleError: false
                    }).done(function (data) {
                        if (data.code == 200) {
                            abp.notify.success(data.msg);
                            table.reload('organization-table');
                            dtree.reload("organization-tree");
                        }
                    }).fail(function (jqXHR) {
                        parent.layer.msg(jqXHR.message, { icon: 5 });
                    }).always(function () {
                        parent.layer.close(waitIndex);
                    });
                });
			}

			window.refresh = function () {
				table.reload('organization-table');
			}
        });
    </script>
}