src/PearAdmin.AbpTemplate.Admin/Areas/TaskCenter/Models/DailyTasks/GetPagedDailyTaskViewModel.cs
using Abp.AutoMapper;
using PearAdmin.AbpTemplate.TaskCenter.DailyTasks.Dto;
using PearAdmin.AbpTemplate.Admin.Models.Common;

namespace PearAdmin.AbpTemplate.Admin.Areas.TaskCenter.Models.DailyTasks
{
    /// <summary>
    /// 日常任务分页模型
    /// </summary>
    [AutoMapTo(typeof(GetPagedDailyTaskInput))]
    public class GetPagedDailyTaskViewModel : PagedViewModel
    {
        public string FilterText { get; set; }
    }
}

src/PearAdmin.AbpTemplate.Admin/Areas/TaskCenter/Controllers/DailyTaskController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Abp.Application.Services.Dto;
using Abp.AspNetCore.Mvc.Authorization;
using Microsoft.AspNetCore.Mvc;
using PearAdmin.AbpTemplate.TaskCenter.DailyTasks;
using PearAdmin.AbpTemplate.TaskCenter.DailyTasks.Dto;
using PearAdmin.AbpTemplate.Admin.Areas.TaskCenter.Models.DailyTasks;
using PearAdmin.AbpTemplate.Admin.Controllers;
using PearAdmin.AbpTemplate.Admin.Models.Common;
using Abp.Web.Models;

namespace PearAdmin.AbpTemplate.Admin.Areas.TaskCenter.Controllers
{
    /// <summary>
    /// 日常任务控制器
    /// </summary>
    [Area("TaskCenter")]
    [AbpMvcAuthorize]
    public class DailyTaskController : AbpTemplateControllerBase
    {
        private readonly IDailyTaskAppService _dailyTaskAppService;

        public DailyTaskController(IDailyTaskAppService dailyTaskAppService)
        {
            _dailyTaskAppService = dailyTaskAppService;
        }

        /// <summary>
        /// 首页
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 获取日常任务列表
        /// </summary>
        /// <returns></returns>
        public async Task<JsonResult> GetDailyTaskList(GetPagedDailyTaskViewModel viewModel)
        {
            var input = PagedViewModelMapToPagedInputDto<GetPagedDailyTaskViewModel, GetPagedDailyTaskInput>(viewModel);
            var pagedDailyTaskList = await _dailyTaskAppService.GetPagedDailyTask(input);
            return Json(new ResponseParamPagedViewModel<DailyTaskDto>(pagedDailyTaskList.TotalCount, pagedDailyTaskList.Items));
        }

        /// <summary>
        /// 创建或更新日常任务
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        public async Task<IActionResult> CreateOrUpdateDailyTask(NullableIdDto<Guid> input)
        {
            var output = await _dailyTaskAppService.GetDailyTaskForEdit(input);

            return View(output);
        }

        /// <summary>
        /// 创建日常任务
        /// </summary>
        /// <param name="input"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<JsonResult> CreateDailyTask([FromBody]CreateDailyTaskDto input)
        {
            await _dailyTaskAppService.CreateDailyTask(input);

            return Json(new ResponseParamViewModel(L("CreateDailyTaskSuccessful")));
        }

        /// <summary>
        /// 更新日常任务
        /// </summary>
        /// <param name="input"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<JsonResult> UpdateDailyTask([FromBody]UpdateDailyTaskDto input)
        {
            await _dailyTaskAppService.UpdateDailyTask(input);

            return Json(new ResponseParamViewModel(L("UpdateDailyTaskSuccessful")));
        }

        /// <summary>
        /// 删除日常任务
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<JsonResult> DeleteDailyTask([FromBody]List<EntityDto<Guid>> input)
        {
            await _dailyTaskAppService.DeleteDailyTask(input);

            return Json(new ResponseParamViewModel(L("DeleteDailyTaskSuccessful")));
        }

        [HttpPost]
        public async Task<JsonResult> ProgressDailyTask([FromBody]EntityDto<Guid> input)
        {
            await _dailyTaskAppService.ProgressDailyTask(input);

            return Json(new ResponseParamViewModel(L("ProgressDailyTaskSuccessful")));
        }

        [HttpPost]
        public async Task<JsonResult> ResolveDailyTask([FromBody]EntityDto<Guid> input)
        {
            await _dailyTaskAppService.ResolveDailyTask(input);

            return Json(new ResponseParamViewModel(L("ResolveDailyTaskSuccessful")));
        }

        [HttpPost]
        public async Task<JsonResult> ReopenDailyTask([FromBody]EntityDto<Guid> input)
        {
            await _dailyTaskAppService.ReopenDailyTask(input);

            return Json(new ResponseParamViewModel(L("ReopenDailyTaskSuccessful")));
        }

        [HttpPost]
        public async Task<JsonResult> QualifyDailyTask([FromBody]EntityDto<Guid> input)
        {
            await _dailyTaskAppService.QualifyDailyTask(input);

            return Json(new ResponseParamViewModel(L("QualifyDailyTaskSuccessful")));
        }

        [HttpPost]
        public async Task<JsonResult> PendDailyTask([FromBody]EntityDto<Guid> input)
        {
            await _dailyTaskAppService.PendDailyTask(input);

            return Json(new ResponseParamViewModel(L("PendDailyTaskSuccessful")));
        }

        [HttpPost]
        public async Task<JsonResult> CloseDailyTask([FromBody]EntityDto<Guid> input)
        {
            await _dailyTaskAppService.CloseDailyTask(input);

            return Json(new ResponseParamViewModel(L("CloseDailyTaskSuccessful")));
        }
    }
}

src/PearAdmin.AbpTemplate.Admin/Areas/TaskCenter/Views/DailyTask/CreateOrUpdateDailyTask.cshtml
@using Abp.Json
@using PearAdmin.AbpTemplate.TaskCenter.DailyTasks.Dto
@model DailyTaskDto

<form class="layui-form" lay-filter="dailyTask-form" style="padding: 15px 0 0 0;">
    <input type="hidden" name="id" />
    <div class="layui-form-item">
        <label class="layui-form-label">名称</label>
        <div class="layui-input-block">
            <input type="text" name="name" lay-verify="required" placeholder="请输入名称" autocomplete="off" class="layui-input">
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">备注</label>
        <div class="layui-input-block">
            <input type="text" name="remark" placeholder="请输入备注" autocomplete="off" class="layui-input">
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">日期范围</label>
        <div class="layui-input-block">
            <input type="text" class="layui-input" id="dateRange" placeholder=" - ">
        </div>
    </div>
    <div class="layui-form-item">
        <div class="layui-input-block">
            <button class="layui-btn layui-hide" lay-submit lay-filter="dailyTask-submit" id="dailyTask-submit">提交</button>
        </div>
    </div>
</form>

@section scripts{
    <script type="text/javascript">
        layui.use(['abp', 'form', 'laydate'], function () {
            var $ = layui.$;
            var abp = layui.abp;
            var form = layui.form;
            var laydate = layui.laydate;

            laydate.render({
                trigger:'click',
                elem: '#dateRange',
                range: true,
                value: '@string.Format("{0} - {1}",Model.StartTime.ToString("yyyy-MM-dd"),Model.EndTime.ToString("yyyy-MM-dd"))',
            });

            function getDateRange() {
                let dateRangeString = $("#dateRange").val();
                if (dateRangeString == undefined || dateRangeString == "") {
                    parent.layer.msg("获取日期范围错误！");
                    return null;
                }
                let dateRangeArray = dateRangeString.split(" - ");
                return {
                    "startTime": dateRangeArray[0],
                    "endTime": dateRangeArray[1]
                }
            }

            var index = parent.layer.getFrameIndex(window.name);
            //parent.layer.iframeAuto(index);

            form.val("dailyTask-form",@Html.Raw(JsonExtensions.ToJsonString(Model, true,false)));
            form.render();

            window.submitForm = function(){
                $("#dailyTask-submit").click();
            }

            form.on('submit(dailyTask-submit)', function (data) {
                let dateRange = getDateRange();
                data.field.startTime = dateRange.startTime;
                data.field.endTime = dateRange.endTime;
                var waitIndex = parent.layer.load(2);
                abp.ajax({
                    url: "@Url.Action(Model.Id !=Guid.Empty ? "UpdateDailyTask":"CreateDailyTask", "DailyTask", new { area="TaskCenter" })",
                    data: JSON.stringify(data.field),
                    abpHandleError: false
                }).done(function (data) {
                    if (data.code == 200) {
                        data.index = index;
                        let parentWindow = parent.selectedWindow().window;
                        parentWindow.saveCallback(data);
                    }
                }).fail(function (jqXHR) {
                    parent.layer.msg(jqXHR.message, { icon: 5 });
                }).always(function () {
                    parent.layer.close(waitIndex);
                });

                return false;
            });
        });
    </script>
}